### ISSUE TITLE
cadc-tomcat and cadc-java are built on Fedora 34, which is EOL

### ISSUE THREAD

**Issue by rob-tw** [opencadc/docker-base#45]
The cadc-tomcat and cadc-java Docker images are built on top of Fedora 34

Fedora 34 reached end-of-life on 7th June 2022 (https://docs.fedoraproject.org/en-US/releases/eol/). This means that it no longer receives updates and fixes, including security related ones.

It is suggested that these Docker images be based on a supported version of Fedora, or ideally a long supported release of an OS, like AlmaLinux, Rocky Linux or Ubuntu, so that they remain current.

**Comment by pdowler** [comment]
Completely agree that I am a little behind on the fedora release, although practically the java + tomcat versions are not far behind:
```
java-11-openjdk-headless-11.0.15.0.10-1.fc34.x86_64
tomcat-9.0.59-3.fc34.noarch
```
compared to something more current like fedora 37 (my dev environment):
```
java-11-openjdk-headless-11.0.18.0.10-1.fc37.x86_64
tomcat-9.0.71-1.fc37
```

I will update to at least fedora 37 asap (requires some testing).

**Comment by pdowler** [comment]
On the second suggestion(s) about a different base distro: yes, I could achieve the same goals with minimal work with a long-term supported distro, but right now I don't get why that would be a better choice than something more volatile like fedora. The goal is to provide a simple base container that is get the right s/w components into (including bug and security fixes), so that's a balances (i) easy to build and maintain, (ii) stability, and (iii) getting access to up-to-date packages and it goes beyond just java and tomcat. 

For example, we have issue #14 proposing using the openjdk base image, but then extra packages that specific apps might require would be much more painful. That would fall down on (iii) and maybe (i).

I can see someone balk at using "stability" and "fedora" in the same sentence, but I mean that in the limited sense of "can I upgrade from f-N to f-N+2 with minimal fuss" and in my experience I can. No one else (even our own images based on cadc-java and cadc-tomcat) really care about these changes, so this is just "stability for maintainer".

So, I am curious why a long term stable OS/distro would be better for using inside containers? We're not running an OS here, just using the distro as a mechanism to get the required s/w and preferred versions installed in a predictable way. Now, if I was running an OS (say in an lxc/lxd container), then I'd have a different opinion.

**Comment by pdowler** [comment]
notes after discussion:
- must keep base image on supported release so security fixes can be pulled with minimal resistence
- rebuild base images and all downstream images (caom2, SI, etc) for security update -- then propagate to production
- maybe rebuild and test base images frequently (without publish) to detect issues asap?

to consider:
- list package requirements for base image
- maybe list extra packages needed by known downstream images (eg wcslib in si/minoc and several caom2 images)?
- maybe always install standard set of supporting packages in base image so downstream only adds java application?
- see if other base image OS support the use cases and could be a viable/better choice

**Comment by pdowler** [comment]
updated to fedora 37 and now including some native libs (required by opencadc JNI libs used in some downstream containers).... not sure how good/bad an idea that is but for now it makes future changes in base distro more easily evaluated

aside: I tried to build on AlmaLinux 8 and 9 but neither include erfa or wcslib in the repos.

**Comment by pdowler** [comment]
closing this as there is a separate issue for package requirements
